# Generated by Django 4.2.16 on 2024-09-28 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_name', models.CharField(max_length=255)),
                ('cost_note', models.CharField(max_length=255)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('cost_date', models.DateField()),
                ('paid', models.IntegerField(blank=True, default=0, null=True)),
                ('paid_date', models.DateField()),
                ('create_cost_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CostSum',
            fields=[
                (
                    'cost_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='pigapp_app.cost',
                    ),
                ),
            ],
            bases=('pigapp_app.cost',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_name', models.CharField(max_length=255)),
                ('invoice_note', models.CharField(max_length=255)),
                ('create_invoice_date', models.DateTimeField(auto_now_add=True)),
                (
                    'enable_invoice',
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CostRepeat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_repeat_name', models.CharField(max_length=255)),
                ('cost_repeat_note', models.CharField(max_length=255)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('cost_repeat_date', models.DateField()),
                ('paid', models.IntegerField(blank=True, default=0, null=True)),
                ('paid_date', models.DateField()),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('create_cost_repeat_date', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CostGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_group_name', models.CharField(max_length=255)),
                ('cost_group_note', models.CharField(max_length=255)),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='cost',
            name='costgroup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='pigapp_app.costgroup'
            ),
        ),
        migrations.AddField(
            model_name='cost',
            name='costrepeat',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='pigapp_app.costrepeat',
            ),
        ),
        migrations.AddField(
            model_name='cost',
            name='dev',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='pigapp_app.dev'
            ),
        ),
        migrations.AddField(
            model_name='cost',
            name='invoice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='pigapp_app.invoice'
            ),
        ),
        migrations.AddField(
            model_name='cost',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='CashFlowGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cash_flow_group_name', models.CharField(max_length=255)),
                ('cash_flow_group_note', models.CharField(max_length=255)),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cash_flow_name', models.CharField(max_length=255)),
                ('cash_flow_note', models.CharField(max_length=255)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('cash_flow_date', models.DateField()),
                ('create_cash_flow_date', models.DateTimeField(auto_now_add=True)),
                (
                    'cashflowgroup',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='pigapp_app.cashflowgroup',
                    ),
                ),
                (
                    'dev',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='pigapp_app.dev'
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='pigapp_app.invoice',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
